### ISSUE TITLE
Unexpected token '<', "<!DOCTYPE "... is not valid JSON) 발생

### ISSUE THREAD

**Issue by polarisjyb** [polarisjyb/iphone-3d-landing-page#1]
Uncaught Error: Could not load /scene.gltf: Unexpected token '<', "<!DOCTYPE "... is not valid JSON)
    at index-bb759d07.esm.js:1624:1
    at _onError (GLTFLoader.js:67:1)
    at Object.onLoad (GLTFLoader.js:88:1)
    at three.module.js:41311:1

현재 이 오류를 해결중에 있습니다.

**Comment by polarisjyb** [comment]
https://discourse.threejs.org/t/syntaxerror-unexpected-token-doctype-is-not-valid-json-at-json-parse-anonymous/42441/11

**Comment by polarisjyb** [comment]
위 링크를 참고하여 오류를 해결할 수 있었습니다.

public 폴더에 src/assets/3D-Model/ 경로에 위치한 textures, scene.bin, scene.gltf 파일을 옮겼습니다.

public 폴더는 정적(Static) 파일들이 저장된 폴더입니다.

파일 자체가 고정되어 있고, 서비스 중에 추가되거나 변경되지 않으며, 외부 환경에 관계 없이 일정한 결과값을 제공하는 파일을 의미합니다.

현재 src 폴더에 저장된 gltf 파일을 따로 변경할 의도가 없기 때문에 public 경로에서 관리하는 것이 적절하다고 생각했습니다.



* Static File: 이미지, CSS, HTML, JS와 같이 해당 내용이 고정되어, 응답할 때 별도 처리 없이 파일 내용을 그대로 보여주면 되는 파일.
